### ISSUE TITLE
Traceability examples

### ISSUE THREAD

**Issue by DagBruck** [PMSFIT/SSPTraceability#70] opened 2024-01-19 08:30 UTC
We need a selection of concrete examples.
- Where are the examples stored?
- Make the examples up-to-date with regards to recent changes.
- Do we need examples?
- Examples must be documented.

**Comment by localhorst87** [comment] 2024-01-19 12:02
In the project UPSIM we applied STMD and can provide examples soon (mid of february).

**Comment by pmai** [comment] 2024-02-23 08:47
As a side-note, I think the examples should be moved to the SSPTraceabilityExamples repo, which we created exactly for this purpose, thus separating the spec from the examples, which allows continuous development of examples independent of the release cycles of the spec.

**Comment by DagBruck** [comment] 2024-02-25 10:37
I'm good with moving the example to another repo, but we should coordinate all SSP-related examples. The pure SSP examples, the traceability examples, etc. And I have a feeling there are quite a few old examples that need updating (or could be deleted).

**Comment by pmai** [comment] 2024-05-17 06:55
Duplicate of #53

**Closed by pmai** 2024-05-17 06:55 UTC
Labels: documentation
